name: servico_terceirizado
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  brasil_fields: ^1.15.0
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  dio: ^5.6.0
  email_validator: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  password_strength_checker: ^1.2.4
  path: ^1.9.0
  path_provider: ^2.1.4
  maps_launcher: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
